apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginxpod
  ports:
  - port: 80
    nodePort: 31010
    targetPort: nginx-port
    protocol: TCP
  type: NodePort
  # Wird nur auf nodes mit disktype ssd ausgeführt (also labels)
  nodeSelector:
    disktype: ssd
