apiVersion: v1
kind: Pod
metad:
  name: nginxwebproxy
  labels:
    app: nginxpod
spec:
  containers:
  - name: nginx
    image: nginx:1.16.0
    ports:
      - containerPort: 80
        name: nginx-port
